export const exampleArray = [
    {
        "bookingID": 101,
        "bookingDetailID": 201,
        "startDate": "2021-01-21T18:30:00",
        "address": "Illinois State University, North University Street, Normal, IL McLean County Illinois 61761",
        "inspectorName": "Grey Stephen",
        "price": 0.0,
        "inspectionTypeID": 14,
        "inspectorPriceID": 2118,
        "inspectionName": "Chimney",
        "reAgentID": 20,
        "cMobile": "9759782141",
        "iMobile": "9759782141",
        "companyName": "Atlas",
        "companyID": 1212,
        "inspectorID": 1140,
        "pictureURL": "http://zapi.yourtechidea.com/Images/Pool.png"
    },
    {
        "bookingID": 102,
        "bookingDetailID": 202,
        "startDate": "2021-01-21T17:30:00",
        "address": "Illinois State University, North University Street, Normal, IL McLean County Illinois 61761",
        "inspectorName": "jitesh agrawal",
        "price": 100.0,
        "inspectionTypeID": 14,
        "inspectorPriceID": 1829,
        "inspectionName": "Chimney",
        "reAgentID": 20,
        "cMobile": "9759782141",
        "iMobile": "9759782141",
        "companyName": "pulsar",
        "companyID": 1209,
        "inspectorID": 1131,
        "pictureURL": "http://zapi.yourtechidea.com/Images/Chimney.png"
    },
    {
        "bookingID": 103,
        "bookingDetailID": 203,
        "startDate": "2021-01-22T18:30:00",
        "address": "Illinois State University, North University Street, Normal, IL McLean County Illinois 61761",
        "inspectorName": "Ajay",
        "price": 0.0,
        "inspectionTypeID": 14,
        "inspectorPriceID": 2118,
        "inspectionName": "Chimney",
        "reAgentID": 20,
        "cMobile": "9759782141",
        "iMobile": "9759782141",
        "companyName": "Atlas",
        "companyID": 1212,
        "inspectorID": 1140,
        "pictureURL": "http://zapi.yourtechidea.com/Images/Home.png"
    },
    {
        "bookingID": 104,
        "bookingDetailID": 204,
        "startDate": "2021-01-22T18:30:00",
        "address": "Illinois State University, North University Street, Normal, IL McLean County Illinois 61761",
        "inspectorName": "Mukesh",
        "price": 100.0,
        "inspectionTypeID": 14,
        "inspectorPriceID": 1829,
        "inspectionName": "Chimney",
        "reAgentID": 20,
        "cMobile": "9759782141",
        "iMobile": "9759782141",
        "companyName": "pulsar",
        "companyID": 1209,
        "inspectorID": 1131,
        "pictureURL": "http://zapi.yourtechidea.com/Images/Pest.png"
    },
    {
        "bookingID": 105,
        "bookingDetailID": 205,
        "startDate": "2021-01-23T18:30:00",
        "address": "Illinois State University, North University Street, Normal, IL McLean County Illinois 61761",
        "inspectorName": "Gaganesh",
        "price": 0.0,
        "inspectionTypeID": 14,
        "inspectorPriceID": 2118,
        "inspectionName": "Chimney",
        "reAgentID": 20,
        "cMobile": "9759782141",
        "iMobile": "9759782141",
        "companyName": "Atlas",
        "companyID": 1212,
        "inspectorID": 1140,
        "pictureURL": "http://zapi.yourtechidea.com/Images/Pool.png"
    },
    {
        "bookingID": 106,
        "bookingDetailID": 206,
        "startDate": "2021-01-23T18:30:00",
        "address": "Illinois State University, North University Street, Normal, IL McLean County Illinois 61761",
        "inspectorName": "Vijayant",
        "price": 100.0,
        "inspectionTypeID": 14,
        "inspectorPriceID": 1829,
        "inspectionName": "Chimney",
        "reAgentID": 20,
        "cMobile": "9759782141",
        "iMobile": "9759782141",
        "companyName": "pulsar",
        "companyID": 1209,
        "inspectorID": 1131,
        "pictureURL": "http://zapi.yourtechidea.com/Images/Roof.png"
    }
]