const colors = {
    white: 'white',
    black: 'black',
    yellow: 'yellow',
    red: 'red',
    lightGray: '#D3D3D3',
    lightWhite: '#f2f2f2',
    gray: 'gray',
    loginBlue: '#6F25C4',
    yellow: '#FFD93E',
    appRed: '#E13E3B',
    appYellow: '#FDD740',
    fullTraspnat: 'transparent',
    toolbar_bg_color: '#28558E',
    leftBG_color: '#5C18AD',
    correctColor: "#00D97E",
    dangerousColor: '#D75B51',
    darkRed: '#FF4934',
    darkViolet: '#5512AD',
    softBlue: '#4990e2',
    strongViolet: '#791ED1',
    veryLightGray:"#F4F4F4",
    txtColor:"#64696D",
    on_board:"#6c24c2",
    on_board_txt_color:"#ffda0d",
    lightGraySec:'#A9A9A9',
    tab_select_color:"#b3003b"

}
export default colors;