const strings = {
    news: 'News',
    sport: 'Sport',
    coronavirus: 'Coronavirus',
    video: 'Video',
    drawer: 'Drawer',
    login: 'Login',
    signup: 'Sign Up',
    fistName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    password: 'Password',
    mobileNumber: 'Mobile Number',
    dob: 'Date of Birth',
    country_code: 'Country Code',
    email_nt_blank: 'Email cannot be blank',
    password_nt_blank: 'Password cannot be blank',
    email_not_valid: 'Please enter valid email address',
    api_timeout: 'Api timeout',
    firstName_nt_blank: 'First name cannot be blank',
    lastname_nt_blank: 'Last name cannot be blank',
    email_nt_blank: 'Email cannot be blank',
    mobile_number_nt_blank: 'Mobile number cannot be blank',
    date_of_birth_nt_blank: 'Date of birth cannot be blank',
    loginFaild: 'Login Failed',
    login_failed_msg: 'Login failed please try again',
    birthday: 'Birthday',
    days: 'Days',
    home: 'Home',
    gifts: 'Gifts',
    friends: 'Friends',
    zodiac: 'Zodiac',
    upcoming_birthday: 'Upcoming Birthdays',
    upcoming_contact_birthday: 'Upcoming Contact Birthdays',
    see_all: 'See all',
    login_successfully: 'Login successfully',
    gift_sent_by_frind: 'Gift sent by friends',
    search: 'Search',
    profile: "Profile",
    send_gift: 'Send Gift',
    about: 'About',
    wishlist: 'Wishlist',
    firstname: 'Firstname',
    lastname: 'Lastname',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    select_birthday: 'Select Birthday',
    update: 'Update',
    country_code_cannot_blank: 'Country code cannot be blank',
    birth_date_nt_blank: 'Birth date cannot be blank',
    comment: 'comment',
    sent_gift: 'Sent gift',
    friends: 'Friends',
    calender: 'Calendar',
    list: 'List',
    friend_request: 'Friend Requests',
    no_friends_found: 'No friends found',
    no_contact_found: 'No contact found',
    select_zodiac: 'Select Zodiac',
    zodiac_sign_cannot_be_blank: 'Zodiac sign cannot be blank',
    lorem_str: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of 'de Finibus Bonorum et Malorum' (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, 'Lorem ipsum dolor sit amet..', comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from 'de Finibus Bonorum et Malorum' by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    friend_with_sign: 'Friends with this sign',
    invitation: 'Invitation',
    message: 'Message',
    giftcard: 'Giftcards',
    currency: 'Currency',
    account: "Account",
    setting: 'Settings',
    name: 'Name',
    username: 'Username',
    location: 'Location',
    phone_number: 'Phone Number',
    email: "E-mail",
    wishlist: 'Wishlist',
    private: 'Private',
    notification: 'Notification',
    when_gift_received: 'When gift received',
    friend_birthday: 'Friend Birthday (days)',
    send: 'Send',
    fullName: 'Full Name',
    trophy: 'Trophies',
    who_can: "Who Can...",
    sent_me_gift: "Send me gift",
    view_my_wishlist: 'View my wishlist',
    sent_me_dm: "Send me DM",
    anyone: 'Anyone',
    just_friend: 'Just friends',
    full_name_nt_blank: "Full name cannot be blank",
    msg_nt_blank: "Message cannot be blank",
    sent_to: "Send to",
    name_username_phone: "Name, Username or Phone number",
    what: 'What',
    where: 'Where',
    when: 'When',
    message: 'Message',
    my_friends: "My Friends",
    select_friend_to: "Sent to cannot be blank",
    what_nt_blank: 'What cannot be blank',
    when_nt_blank: 'When cannot be blank',
    where_nt_blank: "Where cannot be blank",
    message_nt_blank: 'Message cannot be blank',
    invitation_not_sent: "Invitation not set please try after sometime",
    congress: 'Congratulations',
    gift_sent: 'Your gift has been sent!',
    continue: 'Continue',
    share: 'Share',
    gift_card: 'Gift Cards',
    amount: 'Amount',
    what_is_it: "What's it for",
    sent_on: 'Sent on',
    birth_day: 'Birth day',
    specific_date: 'Specific date',
    import_contact: 'Send message from contact',
    my_contact: "Contacts",
    birthday_card: 'Birthday card',
    start_conversation: 'Start Conversation',
    please_Add_amount: "Please add amount",
    price_details: 'Price details',
    price: 'Price',
    tax: 'Tax',
    total: 'Total',
    pay_now: 'Pay Now',
    gift_details: "Gift detail",
    next: 'Next',
    add_this_card_wishlist: "Add this card in your wishlist",
    wishlist_data_not_found: 'Wishlist data not found',
    item_already_wishlist: 'Item already in wishlist',
    item_added_wishlist: 'Item added in wishlist',
    data_nt_found: 'Data not found try again',
    view: "View",
    received_gift: 'Received gifts',
    share_ur_gift_info: 'Share your gift information',
    use: 'Use',
    delete_item: "Remove Item",
    delete_item_msg: "Are you sure want to remove this item",
    save: 'Save',
    okay: 'Okay',
    logout: 'Logout',
    logout_msg: 'Are you sure want to logout this app?',
    yes: 'Yes',
    no: 'No',
    press_again_go_back: 'Please click BACK again to exist',
    my_birthday_msg: "Hooray!! It's your birthday",
    skip: 'Skip',
    never_miss_birthday: 'Never miss a birthday',
    on_boad_1_dummy_txt: " Add your friends, \nwe will send reminders so you know exactly \nwhen to celebrate their birthdays.",
    be_an_awsome_friend: "Be an awesome friend",
    on_boad_2_dummy_txt: " Give a surprise gift or choose one \nfrom your friends wishlist.",
    hpy_birthday_insert_first_name: "Happy birthday \nto insert first name",
    on_board_3_dummy_txt: "For now here's a countdown until your birthday \nMonth, Day, Year.",
    got_it:"Got it!",
    add_contact:'Import contact',
    add_contact_msg:"Are you sure want to import your contacts!",
    inbox:'Inbox',
    send_msg:"Send Message",
    gift:'Gift',
    message:'Message',
    attach_photo:'Attach Photo',
    change:'Change',
    send_dm:'Send DM',
    pls_select_sq_foot:"Please Select square/foot",
    pls_select_properties_home:"Please Select Property",
    pls_select_properties_roof:"Please Select Property",
    pls_select_foundation_home:"Please Select Foundation",
    pls_select_no_pool:"Please Select No. of Pool",
    pls_Select_no_stories:"Please Enter No. of Stories",
    pls_select_no_chimney:'Please Select No. of Chimney',
    pls_enter_first_name:"Please Enter First Name",
    pls_enter_employe_id:"Please Enter Your Employee ID",
    pls_enter_lastname:"Please Enter Last Name",
    pls_enter_password:"Please Enter Your Password",
    pls_enter_email_id:"Please Enter Your Email ID",
    pls_enter_ur_phone_no:"Please Enter Your Phone Number",
    phone_number_should_be_ten_digit:"Phone Number should be of 10 digit",
    pls_enter_zip:"Please Enter Zip",
    history:'History',
    chimney_descrimer:'Note: Chimney quote may vary depending upon whether multiple fireplaces have different equipment/configurations',
    sqare_foot:'Square/Foot',
    property:'Property',
    foundation:'Foundation',
    no_of_pool:"No. of Pool",
    next:'Next',
    previous:'Previous',
}
export default strings;
