let urls = {
	InspectorList:"http://zspectionapi.demoappstore.com/api/inspector-detail",
	StateList: "http://zspectionapi.demoappstore.com/api/states-cites",
	CityList: "http://zspectionapi.demoappstore.com/api/states-cites",
	UploadPic: "http://zspectionapi.demoappstore.com/api/upload",
	RegisterCompany: "http://zapi.yourtechidea.com/api/companies", //http://zspectionapi.demoappstore.com/api/create-user
	InspectionType:"http://zapi.yourtechidea.com/api/inspectiontype",
	FoundationType:"http://zapi.yourtechidea.com/api/foundationtype",
	PriceMatrix:"http://zapi.yourtechidea.com/api/pricematrix",
	CompanyPrices:"http://zapi.yourtechidea.com/api/companyprices",
	// RegisterEstateAgent: "http://zspectionapi.demoappstore.com/api/create-user",
	RegisterInspector: "http://zspectionapi.demoappstore.com/api/inspector",
	//Login: "http://zspectionapi.demoappstore.com/api/login",
	Login: "https://testapi.gohealthnow.com/api/LogIn",
	CompanyLogin:"http://zapi.yourtechidea.com/api/validateUser",
	ForgotPassword: "http://zspectionapi.demoappstore.com/api/forgot-passwod",
	ChangePassword: "http://zspectionapi.demoappstore.com/api/change-password",
	InspectionData: "http://zspectionapi.demoappstore.com/api/inspection-helper",
	AgentProfile: "http://zspectionapi.demoappstore.com/api/change-agent-profile",
	SignUpHelper: "http://zspectionapi.demoappstore.com/api/signup-helper",
	InspectorHelper: "http://zspectionapi.demoappstore.com/api/inspector-helper",
	CreateInspection: "http://zspectionapi.demoappstore.com/api/manage-inspection",
	UpdatePriceMatrix: "http://zspectionapi.demoappstore.com/api/inspector-change-metrix",
	CompanyChangeProfile: "http://zspectionapi.demoappstore.com/api/company-change-profile",
	// InspectionHistory: "http://zspectionapi.demoappstore.com/api/inspection-list",
	NHDFlagUpdate: "http://zspectionapi.demoappstore.com/api/nhd-inspection",
	ValidateCompany: "http://zspectionapi.demoappstore.com/api/validate-user",
	Scheduled: "http://zspectionapi.demoappstore.com/api/inspection-list",
	AgentFavouriteList: "http://zspectionapi.demoappstore.com/api/favorite-inspector-list",
	CompanyInspectionList: "http://zspectionapi.demoappstore.com/api/company-inspection-list",
	InspectionMarkedCompleted: "http://zspectionapi.demoappstore.com/api/inspector-inspection-status",
	OfflineBooking: "http://zapi.yourtechidea.com/api/newbooking",
	ResentBookingOTP: "http://zspectionapi.demoappstore.com/api/inspection-otp",
	InspectorRating: "http://zspectionapi.demoappstore.com/api/inspector-rating",
	SentInvitation: "http://zspectionapi.demoappstore.com/api/inspection-invitation",
	InvitationList: "http://zspectionapi.demoappstore.com/api/invitation-list",
	MarkInvite: "http://zspectionapi.demoappstore.com/api/change-invitation-status",
	CompanyInspectionsForInspector:"http://zapi.yourtechidea.com/api/companyinspectiontype",
	SaveInspector:"http://zapi.yourtechidea.com/api/Inspectors",
	UploadInspectorPic:"http://zapi.yourtechidea.com/api/InspectorPhoto",
	UploadCompanyPic:"http://zapi.yourtechidea.com/api/CompanyPhoto",
	InspectorPrices:"http://zapi.yourtechidea.com/api/inspectorprices",
	CompanyInspectors:"http://zapi.yourtechidea.com/api/CompanyInspectors",
	InspectorDetail:"http://zapi.yourtechidea.com/api/Inspectors",
	RegisterEstateAgent:"http://zapi.yourtechidea.com/api/REAgents",
	UploadAgentPic: "http://zapi.yourtechidea.com/api/REAgentPhoto",
	PropertyTypeForAgent:"http://zapi.yourtechidea.com/api/propertytype",
	GetUser:"http://zapi.yourtechidea.com/api/users",
	CompanyInspectors:'http://zapi.yourtechidea.com/api/CompanyInspectors',
	ValidateEmail:"http://zapi.yourtechidea.com/api/ValidateEmail",
	AgentDetail:"http://zapi.yourtechidea.com/api/REAgents",
	UpdateInspector:"http://zapi.yourtechidea.com/api/UpdateInspector",
	CompanyOwner:'http://zapi.yourtechidea.com/api/companies',
	FindInspectors:'http://zapi.yourtechidea.com/api/SearchInspectors',
	FavoriteInspector:'http://zapi.yourtechidea.com/api/MarkFavorite',
	disableInspector:'http://zapi.yourtechidea.com/api/DisableInspector',
	enableInspector:'http://zapi.yourtechidea.com/api/EnableInspector',
	addBooking:'http://zapi.yourtechidea.com/api/addBooking',
	applyLeave:'http://zapi.yourtechidea.com/api/AddLeave',
	pastBookingList:'http://zapi.yourtechidea.com/api/pastBookinglist',
	upcomingBookingList:'http://zapi.yourtechidea.com/api/currentBookinglist',
	saveAgentProfile:'http://zapi.yourtechidea.com/api/UpdateREAgent',
	saveAgentPic:'http://zapi.yourtechidea.com/api/REAgentPhoto',
	SearchBooking:'http://zapi.yourtechidea.com/api/SearchBooking',
	updateCompany:'http://zapi.yourtechidea.com/api/updatecompany',
	saveCompanyPic:'http://zapi.yourtechidea.com/api/CompanyPhoto',
	fetchdaywisebookingdetails:'http://zapi.yourtechidea.com/api/fetchdaywisebookingdetails',
	cancelBooking:'http://zapi.yourtechidea.com/api/CancelBooking',
	submitRating:'http://zapi.yourtechidea.com/api/ReviewBooking',
	FavInspectors:'http://zapi.yourtechidea.com/api/FavInspectors',


}
module.exports = urls;